# Generated by Django 5.1.3 on 2024-11-24 18:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivias', '0002_trivia_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='trivia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
