services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: tala_trivia_db      # Nombre de la base de datos
      POSTGRES_USER: user              # Nombre de usuario de PostgreSQL
      POSTGRES_PASSWORD: password      # Contraseña de usuario
    ports:
      - "5432:5432"                    # Puerto por defecto de PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tala_network

  web:
    build:
      context: ./backend  # Apunta a la carpeta que contiene el proyecto Django
    volumes:
      - ./backend:/app   # Sincroniza la carpeta backend con el contenedor
    working_dir: /app      # Define el directorio de trabajo en el contenedor
    ports:
      - "8000:8000"        # Puerto para el servidor de desarrollo de Django
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=tala_trivia_db
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
    networks:
      - tala_network

  pgadmin:  
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com   # Email para pgAdmin
      PGADMIN_DEFAULT_PASSWORD: admin           # Contraseña para pgAdmin
    ports:
      - "5050:80"                              # Acceder a pgAdmin en http://localhost:5050
    depends_on:
      - db
    networks:
      - tala_network

networks:
  tala_network:

volumes:
  postgres_data:
