# Generated by Django 5.1.3 on 2024-11-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('jugador', 'Jugador')], default='jugador', max_length=10),
        ),
    ]
